My_Second_Project/Login_app/urls.py
from django.urls import path
from Login_app import views

app_name = 'Login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
]

My_Second_Project/My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('Login_app.urls')),
]

My_Second_Project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    facebook_id = models.URLField(blank=True)
    
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
    def __str__(self):
        return self.user.username
    

My_Second_Project/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')
        
class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

My_Second_Project/Login_app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from Login_app.forms import UserForm, UserInfoForm
from Login_app.models import UserInfo

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def login_page(request):
    return render(request, 'Login_app/login.html', {})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else:
                return HttpResponse("Account is not active!!")
        else:
            HttpResponse("Login Details are Wrong!")
    
    else:
        return render(request, 'Login_app/login.html',context={})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))

def index(request):
    dict = {}
    return render(request, 'Login_app/index.html', context=dict)

def register(request):
    
    registered = False
    
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)
        
        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            
            user_info = user_info_form.save(commit=False)
            user_info.user = user
            
            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
                
            user_info.save()
            
            registered = True
        else:
            print(user_form.errors, user_info_form.errors)
    else:    
        user_form = UserForm()
        user_info_form = UserInfoForm()
        
    dict = {'user_form': user_form, 'user_info_form': user_info_form, 'registered': registered}
    return render(request, 'Login_app/register.html', context=dict)

My_Second_Project/Login_app/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'Login_app:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Login_app:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Login_app:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Login_app:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container" style="padding-top: 20px;">
        {% block body_block %} {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

My_Second_Project/Login_app/templates/Login_app/index.html
{% extends 'Login_app/base.html' %} {% block bodyblock %}
<h1>Index Page</h1>
{% endblock %}

My_Second_Project/Login_app/templates/Login_app/login.html
{% extends 'Login_app/base.html' %} {% block body_block %}
<h3>Please Login:</h3>
<form action="{% url 'Login_app:user_login' %}" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username" required class="form-control">
    <label for="password">Password</label>
    <input type="password" name="password" placeholder="Enter Password" required class="form-control"> {% csrf_token %}
    <br>
    <input type="submit" name="submit" value="Login">
</form>
{% endblock %}

My_Second_Project/Login_app/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}' {% load static %} {% block body_block %} {% if registered %}
<div class="alert alert-success">Congratulations! Registration is Successful!!</div>
{% else %}
<form enctype="multipart/form-data" method="POST">
    {{user_form.as_p}} {{user_info_form.as_p}} {% csrf_token %}
    <input type="submit" name="submit" value="Register">
</form>
{% endif %} {% endblock %}