My_First_Project/My_First_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('first_app.urls')),
]

My_First_Project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_album/',views.album_form, name='album_form'),
    path('add_musician/', views.musician_form, name='musician_form'),
    path('album_list/<int:artist_id>/', views.album_list, name='album_list'),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name='edit_artist'),
    path('edit_album/<int:album_id>/', views.edit_album, name='edit_album'),
]

My_First_Project/first_app/models.py
from django.db import models

# Create your models here.

class Musician(models.Model):
    # id = models.AutoField(Primarh_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=50)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Album(models.Model):
    # id = models.AutoField(Primarh_key=True)
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()

    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excellent"),
    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + ", Rating" + str(self.num_stars)

My_First_Project/first_app/forms.py
from django import forms 
from first_app import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"
        
        
class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = models.Album
        fields = "__all__"

My_First_Project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Musician, Album
from first_app import forms
from django.db.models import Avg

# Create your views here.

def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'title': "Home Page",'musician_list':musician_list}
    return render(request, 'first_app/index.html', context=diction)


def album_list(request, artist_id):  
    artist_info = Musician.objects.get(pk=artist_id)
    album_list = Album.objects.filter(artist=artist_id).order_by('name','release_date')
    artist_rating = Album.objects.filter(artist=artist_id).aggregate(Avg('num_stars'))
    diction = {'title': "List of Albums",'artist_info': artist_info,'album_list': album_list,'artist_rating': artist_rating}
    return render(request,'first_app/album_list.html', context=diction)

def musician_form(request):
    form = forms.MusicianForm()
    
    if request.method == 'POST':
        form = forms.MusicianForm(request.POST)
        
        if form.is_valid():
            form.save(commit=True)
            return index(request)
            
    diction = ({'title': "Add Musicians",'musician_form':form})
    return render(request,'first_app/musician_form.html', context=diction)

def album_form(request):
    form = forms.AlbumForm()
    
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)
        
        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = ({'title': "Add Albums",'album_form': form})
    return render(request,'first_app/album_form.html', context=diction)

def edit_artist(request, artist_id):
    artist_info = Musician.objects.get(artist=artist_id)
    form = forms.MusicianForm(instance=artist_info)
    
    if request.method == 'POST':
        form = forms.MusicianForm(request.POST, instance=artist_info)
        
        if form.is_valid():
            form.save(commit=True)
            return album_list(request, artist_id)
        
    diction = {'edit_form': form}
    return render(request,'first_app/edit_artist.html', context=diction)

def edit_album(request, album_id):
    album_info = Album.objects.get(pk=album_id)
    form = forms.AlbumForm(instance=album_info)
    
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST, instance=album_info)
        
        if form.is_valid():
            form.save(commit=True)
            
    diction={'edit_form': form}
    return render(request, 'first_app/edit_album.html', context=diction)

My_First_Project/templates/first_app/album_form.html
{% extends 'first_app/base.html' %} {% block body_block %}
<h3>Album Form:</h3>
<form method="POST">
    {{album_form.as_p}} {% csrf_token %}
    <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
</form>
{% endblock %}

My_First_Project/templates/first_app/album_list.html
{% extends 'first_app/base.html' %} {% block body_block %}
<h4>Artist Name: {{ artist_info.first_name }} {{ artist_info.last_name }}</h4>
<h4>Instrument: {{ artist_info.instrument }}</h4>
<h4>Artist Rating: {{ artist_rating.num_stars__avg }}</h4>
<h3>List of Albums</h3>
<a href="{% url 'first_app:edit_artist' artist_id=artist_info.id%}" class="btn btn-primary btn-sm">Edit</a>
<table class="table table-bordered">
    <tr>
        <th>Album Name</th>
        <th>Release Date</th>
        <th>Rating</th>
    </tr>
    {% for album in album_list %}
    <tr>
        <td><a href="{%url 'first_app:edit_album' album_id=album.id%}">{{ album.name }}</td>
        <td>{{ album.release_date|date:"M d, Y" }}</td>
        <td>{{ album.num_stars }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

My_First_Project/templates/first_app/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'first_app:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first_app:musician_form' %}">Add Musician</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first_app:album_form' %}">Add Album</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body_block %} {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

My_First_Project/templates/first_app/edit_album.html
{% extends 'first_app/base.html' %} {% block body_block %}
<h4>Edit Album</h4>
<form method="POST">
    {{edit_form.as_p}} {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-success btn-sm">
</form>
{% endblock %}

My_First_Project/templates/first_app/edit_artist.html
{% extends 'first_app/base.html' %} {% block body_block %}
<h4>Edit Artist</h4>
<form method="POST">
    {{ edit_form.as_p}} {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>
{% endblock %}

My_First_Project/templates/first_app/index.html
{% extends 'first_app/base.html' %} {% block body_block %}
<h3>List of Musicians</h3>
<ul>
    {% if musician_list %} {% for musician in musician_list %}
    <li><a href="{% url 'first_app:album_list' artist_id=musician.id %}">{{musician.first_name}} {{musician.last_name}}</a></li>
    {% endfor %} {% else %}
    <h4>No musicians in the list</h4>
    {% endif %}
</ul>
{% endblock %}

My_First_Project/templates/first_app/musician_form.html
{% extends 'first_app/base.html' %} {% block body_block %}
<h3>Musician Form:</h3>
<form method="POST">
    {{musician_form.as_p}} {% csrf_token %}
    <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
</form>
{% endblock %}